export interface Country {
  slug: string
  name: string
  continent: string
  coverImage: string
  flagEmoji: string
  halalScore: number
  capitalCity: string
  population: string
  muslimPercentage: string
  currency: string
  bestTime: string
  description: string
  shortDescription: string
  halalFoodAvailability: 'Excellent' | 'Bon' | 'Moyen' | 'Difficile'
  mosquesPresence: 'Partout' | 'Dans les villes' | 'Rares'
  alcoholPolicy: 'Interdit' | 'Rare' | 'Disponible mais évitable' | 'Très présent'
  dresscode: string
  mainCities: { name: string; slug: string; description: string }[]
  relatedGuides: { slug: string; title: string; type: 'guide' | 'blog' }[]
  faqs: { question: string; answer: string }[]
  tips: string[]
  tags: string[]
}

export const countries: Country[] = [
  {
    slug: 'turquie',
    name: 'Turquie',
    continent: 'Europe / Asie',
    coverImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1400&q=85',
    flagEmoji: '🇹🇷',
    halalScore: 5,
    capitalCity: 'Ankara',
    population: '85 millions',
    muslimPercentage: '99%',
    currency: 'Lire turque (TRY)',
    bestTime: 'Avril–juin · Septembre–novembre',
    shortDescription: 'L\'empire ottoman revit à travers ses mosquées millénaires et sa gastronomie 100% halal.',
    description: 'La Turquie est incontestablement la destination halal reine pour les voyageurs musulmans francophones. Pays à 99% musulman, elle offre une liberté totale : nourriture halal partout, mosquées à chaque coin de rue, appel à la prière cinq fois par jour. D\'Istanbul à la Cappadoce, de la côte égéenne aux monts du Taurus, la Turquie est une mosaïque de civilisations islamiques, de paysages époustouflants et d\'une gastronomie d\'une richesse incomparable. Accessible en vol direct depuis Paris (3h30), abordable, sécurisée et accueillante — elle cumule tous les avantages pour un voyage halal parfait.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste recommandée dans les mosquées et quartiers conservateurs. Couverture des épaules et des genoux obligatoire pour visiter les mosquées.',
    mainCities: [
      { name: 'Istanbul', slug: 'istanbul', description: 'La perle du Bosphore, entre Europe et Asie, 3 000 mosquées, gastronomie halal incomparable.' },
      { name: 'Cappadoce', slug: 'cappadoce', description: 'Paysages lunaires, montgolfières et cave-hôtels. L\'expérience la plus unique de Turquie.' },
      { name: 'Antalya', slug: 'antalya', description: 'La riviera turque — plages immaculées, resorts halal et histoire antique.' },
      { name: 'Bursa', slug: 'bursa', description: 'Première capitale ottomane, grande mosquée, marché couvert et bains thermaux.' },
    ],
    relatedGuides: [
      { slug: 'istanbul-guide-halal-complet', title: 'Istanbul halal : guide complet 2026', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
    ],
    faqs: [
      { question: 'La nourriture est-elle entièrement halal en Turquie ?', answer: 'Oui, à 99%. La quasi-totalité des restaurants en Turquie servent de la viande halal par défaut, notamment dans les quartiers traditionnels. Dans les zones très touristiques ou les établissements internationaux, une certification halal peut être demandée.' },
      { question: 'Peut-on trouver de l\'alcool en Turquie ?', answer: 'L\'alcool est légal en Turquie mais facilement évitable. Dans les quartiers conservateurs et la plupart des restaurants traditionnels, aucun alcool n\'est servi. Evitez simplement les bars et restaurants de type occidental dans les zones touristiques.' },
      { question: 'Quelles mosquées visiter absolument en Turquie ?', answer: 'La Mosquée Bleue et Sainte-Sophie à Istanbul sont incontournables. La Grande Mosquée de Bursa (Ulu Camii), la Mosquée Selimiye à Edirne (classée UNESCO) et la Mosquée Hacı Bayram à Ankara complètent le tableau.' },
      { question: 'Quel est le meilleur moment pour visiter la Turquie ?', answer: 'Avril-juin et septembre-novembre offrent les meilleures conditions : températures agréables (20-28°C), moins de touristes. Juillet-août est la haute saison balnéaire (chaud, bondé). Décembre-février est idéal pour visiter Istanbul et la Cappadoce sous la neige.' },
    ],
    tips: [
      'La carte Istanbulkart est indispensable pour les transports en commun à Istanbul.',
      'Negocier est une pratique normale dans les bazars — commencez à 50% du prix affiché.',
      'Le hamam est une expérience culturelle incontournable — choisir un établissement traditionnel dans les vieux quartiers.',
      'Les restaurants autour des grandes mosquées touristiques pratiquent souvent des prix majorés — s\'éloigner d\'une rue ou deux.',
      'Le visa e-Visa est obtenu en quelques minutes sur evisa.gov.tr pour les ressortissants français.',
    ],
    tags: ['Culture ottomane', 'Gastronomie', 'Histoire', 'Architecture', 'Mer', 'Montagne'],
  },
  {
    slug: 'maroc',
    name: 'Maroc',
    continent: 'Afrique',
    coverImage: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=1400&q=85',
    flagEmoji: '🇲🇦',
    halalScore: 5,
    capitalCity: 'Rabat',
    population: '37 millions',
    muslimPercentage: '99%',
    currency: 'Dirham marocain (MAD)',
    bestTime: 'Mars–mai · Septembre–novembre',
    shortDescription: 'Pays halal par nature, le Maroc offre médinas, riads et gastronomie dans un écrin islamique authentique.',
    description: 'Le Maroc est la destination halal la plus prisée des Français musulmans — et pour cause. À 2h30 de vol de Paris, ce pays à 99% musulman propose un voyage sans aucun compromis : nourriture halal dans chaque restaurant, rythme de vie islamique naturel, architecture arabo-andalouse magnifique et accueil chaleureux. Marrakech, Fès, Chefchaouen, les dunes du Sahara — chaque recoin du Maroc est une carte postale. Pour les familles, les couples et les voyageurs solo, le Maroc répond à toutes les attentes.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Rare',
    dresscode: 'Tenue modeste respectée dans les médinas et les mosquées. Les femmes voilées sont pleinement respectées.',
    mainCities: [
      { name: 'Marrakech', slug: 'marrakech', description: 'La ville ocre et ses souks mythiques, riads somptueux et place Jemaa el-Fna.' },
      { name: 'Fès', slug: 'fes', description: 'La médina de Fès, classée UNESCO, est l\'une des vieilles villes islamiques les mieux préservées au monde.' },
      { name: 'Chefchaouen', slug: 'chefchaouen', description: 'La ville bleue nichée dans le Rif, joyau photographique du Maroc.' },
      { name: 'Essaouira', slug: 'essaouira', description: 'Cité des alizés, architecture blanche et bleue, ambiance détendue en bord de mer.' },
    ],
    relatedGuides: [
      { slug: 'marrakech-guide-halal', title: 'Marrakech halal : guide complet 2026', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Tout est-il halal au Maroc ?', answer: 'Oui, quasi intégralement. Le Maroc étant un État islamique, la totalité des restaurants, boucheries et établissements alimentaires respectent les préceptes halal par défaut. Aucune vérification n\'est nécessaire.' },
      { question: 'Quelle est la meilleure période pour visiter le Maroc ?', answer: 'Mars à mai et septembre à novembre sont idéaux : températures de 20-25°C, ciel bleu, moins de touristes. Juillet-août est très chaud (40°C+ dans l\'intérieur), décembre-février est doux et agréable.' },
      { question: 'Quel budget prévoir pour un voyage au Maroc ?', answer: 'Le Maroc est très abordable. Un riad de standing moyen à Marrakech coûte 50-80€/nuit, les restaurants locaux de 3 à 8€. Budget tout compris : 60-150€/jour selon le confort souhaité.' },
      { question: 'Faut-il un visa pour le Maroc ?', answer: 'Non, les ressortissants français, belges et suisses n\'ont pas besoin de visa pour le Maroc. Un séjour de moins de 90 jours est libre avec passeport ou carte d\'identité.' },
    ],
    tips: [
      'Négocier est culturellement attendu dans tous les souks — ne jamais payer le premier prix.',
      'Se méfier des "guides" non officiels aux abords des médinas — opter pour une agence locale agréée.',
      'Les riads de la médina offrent l\'expérience la plus authentique et sont souvent moins chers que les hôtels de chaîne.',
      'L\'eau du robinet n\'est pas recommandée — boire uniquement de l\'eau en bouteille.',
      'Le dirham marocain ne peut pas être sorti du territoire — changer uniquement ce dont vous avez besoin.',
    ],
    tags: ['Médina', 'Souks', 'Désert', 'Gastronomie', 'Architecture', 'Plage'],
  },
  {
    slug: 'emirats-arabes-unis',
    name: 'Émirats Arabes Unis',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1400&q=85',
    flagEmoji: '🇦🇪',
    halalScore: 5,
    capitalCity: 'Abu Dhabi',
    population: '10 millions',
    muslimPercentage: '76% (résidents)',
    currency: 'Dirham des EAU (AED)',
    bestTime: 'Novembre–avril',
    shortDescription: 'Modernité absolue et luxe halal garanti dans le cadre d\'un État islamique ultra-développé.',
    description: 'Les Émirats Arabes Unis représentent le summum du tourisme halal contemporain. État islamique à 100%, la certification halal y est obligatoire pour tous les établissements de restauration — une garantie unique au monde. Dubai et Abu Dhabi combinent des gratte-ciels futuristes, des plages de sable blanc, le shopping de luxe, des musées de classe mondiale et une infrastructure hôtelière 5 étoiles dans un cadre entièrement conforme aux valeurs islamiques. Une destination idéale pour les familles aisées et les voyageurs exigeants.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue correcte dans les espaces publics et centres commerciaux. Tenues de plage réservées aux zones balnéaires.',
    mainCities: [
      { name: 'Dubaï', slug: 'dubai', description: 'La ville la plus spectaculaire du monde — Burj Khalifa, Palm Jumeirah, shopping de luxe.' },
      { name: 'Abu Dhabi', slug: 'abu-dhabi', description: 'Capitale et siège de la Grande Mosquée Sheikh Zayed, l\'une des plus belles du monde.' },
      { name: 'Sharjah', slug: 'sharjah', description: 'L\'Émirat culturel, plus conservateur, avec d\'excellents musées islamiques.' },
    ],
    relatedGuides: [
      { slug: 'dubai-guide-halal-2026', title: 'Dubai halal : guide complet 2026', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
    ],
    faqs: [
      { question: 'La nourriture est-elle garantie halal aux EAU ?', answer: 'Oui, par obligation légale. Tous les restaurants des EAU doivent obtenir une certification halal pour opérer. Vous pouvez manger en toute confiance dans n\'importe quel établissement.' },
      { question: 'Quel est le meilleur moment pour visiter Dubai ?', answer: 'Novembre à avril est la saison idéale avec des températures de 20-28°C. Juillet-août est extrêmement chaud (45°C+) mais les prix des hôtels chutent drastiquement.' },
      { question: 'Quel budget prévoir pour Dubai ?', answer: 'Dubai peut être abordable ou luxueux selon vos choix. Budget "confort" : 150-250€/jour. Budget "luxe" : 400€+/jour. Les centres commerciaux, plages publiques et certaines activités sont gratuits ou peu coûteux.' },
      { question: 'Y a-t-il des plages séparées pour hommes et femmes à Dubai ?', answer: 'Certaines plages et piscines d\'hôtels proposent des créneaux séparés sur demande. La plupart des hôtels 5 étoiles ont des options adaptées aux familles conservatrices.' },
    ],
    tips: [
      'Le Dubai Mall et les transports en commun (Metro) sont excellents et très économiques.',
      'Uber et Careem sont fiables et moins chers que les taxis traditionnels.',
      'Eviter les taxis non officiels à la sortie des aéroports.',
      'La Mosquée Jumeirah est ouverte aux non-musulmans avec visites guidées — à ne pas manquer.',
      'Les activités en famille comme le parc aquatique Atlantis ou le désert peuvent être réservées à l\'avance avec des réductions significatives.',
    ],
    tags: ['Luxe', 'Shopping', 'Architecture', 'Désert', 'Plage', 'Famille'],
  },
  {
    slug: 'malaisie',
    name: 'Malaisie',
    continent: 'Asie du Sud-Est',
    coverImage: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1400&q=85',
    flagEmoji: '🇲🇾',
    halalScore: 5,
    capitalCity: 'Kuala Lumpur',
    population: '33 millions',
    muslimPercentage: '63%',
    currency: 'Ringgit malaisien (MYR)',
    bestTime: 'Toute l\'année (éviter mousson mai–octobre)',
    shortDescription: 'N°1 mondial du tourisme halal — certification JAKIM, gastronomie fusion et modernité incomparables.',
    description: 'La Malaisie est régulièrement couronnée meilleure destination halal mondiale par le Global Muslim Travel Index. Et pour cause : le système de certification JAKIM (Département des affaires islamiques de Malaisie) est le plus rigoureux au monde. Chaque restaurant, hôtel et produit alimentaire doit renouveler annuellement sa certification. Pour le voyageur musulman, c\'est une liberté totale et une tranquillité d\'esprit absolue. Kuala Lumpur combine la modernité des tours Petronas, une gastronomie halal fusion extraordinaire (influences malaise, chinoise et indienne) et des prix très inférieurs à l\'Europe.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste respectueuse dans les mosquées et zones rurales. Plus décontracté dans les quartiers urbains modernes.',
    mainCities: [
      { name: 'Kuala Lumpur', slug: 'kuala-lumpur', description: 'La capitale halal du monde — tours Petronas, food courts certifiés, vie nocturne islamique.' },
      { name: 'Penang', slug: 'penang', description: 'Île patrimoniale UNESCO avec une scène gastronomique halal exceptionnelle.' },
      { name: 'Malacca', slug: 'malacca', description: 'Port historique classé UNESCO, carrefour des civilisations islamo-malaise.' },
      { name: 'Langkawi', slug: 'langkawi', description: 'Archipel tropical paradisiaque avec des hôtels halal de luxe.' },
    ],
    relatedGuides: [
      { slug: 'malaisie-halal-destination', title: 'Malaisie : la destination n°1 mondiale pour les musulmans', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
    ],
    faqs: [
      { question: 'Qu\'est-ce que la certification JAKIM ?', answer: 'JAKIM (Jabatan Kemajuan Islam Malaysia) est le département gouvernemental malaisien qui certifie tous les établissements halal du pays. Cette certification annuelle renouvelable est la plus stricte au monde — voir le logo JAKIM = certitude absolue.' },
      { question: 'La Malaisie est-elle une bonne destination pour les familles ?', answer: 'Absolument. La Malaisie est l\'une des destinations familiales halal les plus complètes : parcs aquatiques, parcs naturels, plages, activités culturelles, restaurants adaptés aux enfants, transports excellents.' },
      { question: 'Quel est le coût de la vie en Malaisie ?', answer: 'La Malaisie est très abordable. Un repas halal certifié dans un food court coûte 2-4€. Un hôtel de standing moyen 40-80€/nuit. Budget total confortable : 60-100€/jour.' },
      { question: 'Quelle langue parle-t-on en Malaisie ?', answer: 'Le Bahasa Malaysia (malais) est la langue officielle, mais l\'anglais est largement parlé dans les villes et les zones touristiques. Pas de barrière linguistique pour les voyageurs francophones.' },
    ],
    tips: [
      'La carte Touch \'n Go est indispensable pour les transports en commun à KL.',
      'Grab est l\'application de transport de référence — fiable et moins cher que les taxis.',
      'Les food courts des centres commerciaux offrent une diversité culinaire halal certifiée incomparable.',
      'Préparer des tenues légères — chaleur et humidité élevées toute l\'année.',
      'La période du Thaïpusam (janvier-février) offre un spectacle culturel unique à Batu Caves.',
    ],
    tags: ['Halal certifié', 'Gastronomie', 'Nature', 'Moderne', 'Famille', 'Budget'],
  },
  {
    slug: 'arabie-saoudite',
    name: 'Arabie Saoudite',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=1400&q=85',
    flagEmoji: '🇸🇦',
    halalScore: 5,
    capitalCity: 'Riyad',
    population: '36 millions',
    muslimPercentage: '100%',
    currency: 'Riyal saoudien (SAR)',
    bestTime: 'Septembre–avril',
    shortDescription: 'Gardienne des deux mosquées saintes, l\'Arabie Saoudite est le voyage spirituel ultime de tout musulman.',
    description: 'L\'Arabie Saoudite est la terre sainte de l\'islam, accueillant chaque année des millions de pèlerins pour l\'Omra et le Hajj. La Mecque et Médine sont les destinations spirituelles les plus importantes pour tout musulman. Depuis 2019, l\'Arabie Saoudite a ouvert ses portes au tourisme mondial avec des e-visas facilités et de nombreuses nouvelles attractions (AlUla, Diriyah, NEOM). Au-delà de la dimension spirituelle, le pays offre un patrimoine archéologique exceptionnel et une gastronomie 100% halal dans un cadre islamique total.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Interdit',
    dresscode: 'Tenue islamique stricte pour les femmes dans les lieux saints. Dans les zones touristiques modernes, tenue modeste suffisante.',
    mainCities: [
      { name: 'La Mecque', slug: 'la-mecque', description: 'La ville la plus sainte de l\'islam — accessible uniquement aux musulmans.' },
      { name: 'Médine', slug: 'medine', description: 'Ville du Prophète ﷺ et de la Mosquée an-Nabawi — deuxième lieu saint de l\'islam.' },
      { name: 'Riyad', slug: 'riyad', description: 'Capitale moderne en pleine transformation, musées et centres commerciaux de classe mondiale.' },
      { name: 'AlUla', slug: 'alula', description: 'Site archéologique exceptionnel — Hegra classée UNESCO, splendeurs du désert.' },
    ],
    relatedGuides: [
      { slug: 'omra-2026-guide-complet', title: 'Omra 2026 : guide complet pour préparer votre pèlerinage', type: 'guide' },
      { slug: 'ramadan-voyage-guide', title: 'Voyager pendant le Ramadan : guide complet', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Les non-musulmans peuvent-ils entrer en Arabie Saoudite ?', answer: 'Oui, depuis 2019, l\'Arabie Saoudite délivre des visas touristiques aux non-musulmans. En revanche, La Mecque et Médine (centre-ville) restent réservées aux musulmans.' },
      { question: 'Comment obtenir un visa pour l\'Omra ?', answer: 'Via le portail officiel nusuk.sa pour un e-visa Omra (24-72h de délai) ou via une agence agréée française. Documents requis : passeport valide 6 mois + vaccination méningocoque ACWY.' },
      { question: 'Quelle est la différence entre Omra et Hajj ?', answer: 'L\'Omra est le "petit pèlerinage", réalisable toute l\'année, sans condition préalable. Le Hajj est le "grand pèlerinage", obligatoire pour tout musulman en capacité, à une date précise du calendrier islamique (Dhul Hijja). Le Hajj est l\'un des 5 piliers de l\'islam.' },
      { question: 'Quel budget prévoir pour l\'Omra depuis la France ?', answer: 'Vol Paris–Djeddah (350-700€) + hébergement (80-300€/nuit selon standing et distance de la Kaaba) + repas (30-60€/jour). Les forfaits Omra tout compris débutent à 1 200€ (hors saison) et peuvent dépasser 5 000€ pendant le Ramadan.' },
    ],
    tips: [
      'Réserver l\'Omra 3 à 6 mois à l\'avance, surtout pendant le Ramadan où les hôtels se remplissent des mois avant.',
      'L\'application Nusuk (officielle) est indispensable pour les réservations et informations en temps réel.',
      'Choisir l\'hôtel le plus proche de la Masjid al-Haram pour minimiser les distances à pied.',
      'S\'hydrater constamment — la chaleur peut atteindre 45°C en été à La Mecque.',
      'Emporter des vêtements adaptés (ihram pour les hommes, tenues amples pour les femmes).',
    ],
    tags: ['Spiritualité', 'Omra', 'Hajj', 'Pèlerinage', 'Islam', 'Patrimoine'],
  },
  {
    slug: 'egypte',
    name: 'Égypte',
    continent: 'Afrique',
    coverImage: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=1400&q=85',
    flagEmoji: '🇪🇬',
    halalScore: 5,
    capitalCity: 'Le Caire',
    population: '106 millions',
    muslimPercentage: '90%',
    currency: 'Livre égyptienne (EGP)',
    bestTime: 'Octobre–avril',
    shortDescription: 'Des pyramides de Gizeh à Al-Azhar, l\'Égypte conjugue merveilles antiques et richesse islamique.',
    description: 'L\'Égypte est une destination unique au monde : nulle part ailleurs on ne trouve cette combinaison d\'histoire antique (pyramides, sphinx, temples pharaoniques) et de richesse islamique (Al-Azhar, le Khan el-Khalili, 3 000 mosquées au Caire). Pays à 90% musulman, la nourriture halal est la norme absolue. Le Caire fascine par son intensité, Louxor et Assouan éblouissent par leurs temples, et les stations balnéaires de Charm el-Cheikh et Hurghada offrent mer et soleil dans un cadre accessible.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste dans les villes et les sites religieux. Plus de liberté dans les stations balnéaires.',
    mainCities: [
      { name: 'Le Caire', slug: 'le-caire', description: 'La mère du monde — pyramides, Al-Azhar, khan el-Khalili et une énergie unique.' },
      { name: 'Louxor', slug: 'louxor', description: 'La plus grande ville-musée à ciel ouvert du monde, temple de Karnak, Vallée des Rois.' },
      { name: 'Alexandrie', slug: 'alexandrie', description: 'Perle méditerranéenne, bibliothèque, gastronomie de fruits de mer, ambiance cosmopolite.' },
      { name: 'Charm el-Cheikh', slug: 'charm-el-cheikh', description: 'Plongée en mer Rouge, complexes hôteliers halal, coraux exceptionnels.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'ramadan-voyage-guide', title: 'Voyager pendant le Ramadan', type: 'guide' },
    ],
    faqs: [
      { question: 'Est-ce sûr de voyager en Égypte en 2026 ?', answer: 'Les zones touristiques (Le Caire, Louxor, Charm el-Cheikh, Hurghada) sont sûres et accueillent des millions de touristes chaque année. Le Ministère français des affaires étrangères recommande une vigilance normale dans ces zones.' },
      { question: 'Faut-il un visa pour l\'Égypte ?', answer: 'Oui, mais il est obtenu facilement en e-visa sur visa2egypt.gov.eg pour environ 25$, ou à l\'arrivée à l\'aéroport (25$). Valable 30 jours.' },
      { question: 'Quel budget pour un voyage en Égypte ?', answer: 'L\'Égypte est très abordable. Un repas local coûte 2-5€, un hôtel de qualité 30-60€/nuit. Budget confort : 50-100€/jour. Les billets d\'entrée des sites archéologiques (pyramides, temples) sont les principales dépenses touristiques.' },
    ],
    tips: [
      'Négocier est indispensable pour taxis, calèches et souvenirs — toujours demander le prix avant.',
      'Boire uniquement de l\'eau en bouteille — éviter l\'eau du robinet.',
      'Visiter les pyramides à l\'ouverture (7h) pour éviter la chaleur et les foules.',
      'Les pourboires (bakchich) font partie de la culture — prévoir de la monnaie.',
      'Se faire accompagner d\'un guide local pour les bazars — cela évite les arnaques et enrichit la visite.',
    ],
    tags: ['Histoire', 'Archéologie', 'Pyramides', 'Islam', 'Mer Rouge', 'Culture'],
  },
  {
    slug: 'maldives',
    name: 'Maldives',
    continent: 'Asie du Sud',
    coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1400&q=85',
    flagEmoji: '🇲🇻',
    halalScore: 4,
    capitalCity: 'Malé',
    population: '540 000',
    muslimPercentage: '100%',
    currency: 'Rufiyaa maldivienne (MVR)',
    bestTime: 'Novembre–avril',
    shortDescription: 'Lagons turquoise, villas sur pilotis et 100% pays musulman — le paradis accessible aux couples halal.',
    description: 'Les Maldives sont le paradis sur terre — et pour les couples musulmans, c\'est une bénédiction particulière. Pays islamique à 100%, l\'alcool est légalement interdit sur les îles habitées locales. Les resorts touristiques proposent des options halal-friendly avec villas privées, plages exclusives et piscines privées — permettant une intimité totale pour les jeunes mariés et les couples. Les lagons turquoise aux eaux cristallines, les fonds marins d\'une richesse inouïe et la quiétude absolue font des Maldives une destination lune de miel idéale.',
    halalFoodAvailability: 'Bon',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste sur les îles habitées. Plus de liberté dans les resorts privés.',
    mainCities: [
      { name: 'Malé', slug: 'male', description: 'Capitale animée avec la Grande Mosquée du Vendredi, marché local coloré.' },
      { name: 'Maafushi', slug: 'maafushi', description: 'Île locale avec guest houses abordables, budget halal-friendly.' },
      { name: 'Atolls du Nord', slug: 'atolls-nord', description: 'Resorts de luxe avec overwater bungalows, snorkeling et plongée exceptionnels.' },
    ],
    relatedGuides: [
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : 10 destinations romantiques', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Les Maldives sont-elles halal-friendly pour les couples musulmans ?', answer: 'Oui. Les Maldives sont un État islamique à 100%. Les resorts proposent de la nourriture halal, des espaces privés et une discrétion absolue. Les villas avec piscines privées sur pilotis offrent une intimité totale pour les couples.' },
      { question: 'Quel est le meilleur moyen de rejoindre son resort aux Maldives ?', answer: 'Après l\'atterrissage à Malé, vous rejoignez votre resort en hydravion (20-45 min, très cher), en speed boat (30-90 min, moins cher) ou en bateau local pour les îles proches.' },
      { question: 'Quel budget prévoir pour les Maldives ?', answer: 'Les Maldives s\'adaptent à tous les budgets. Les guest houses sur îles locales : 80-150€/nuit. Les resorts d\'entrée de gamme : 200-400€/nuit. Les resorts de luxe : 500€ à 5 000€/nuit.' },
    ],
    tips: [
      'Réserver 4 à 6 mois à l\'avance pour les meilleures offres, surtout en haute saison.',
      'Les îles locales (Maafushi, Fulidhoo) sont 3 à 5 fois moins chères que les resorts privés.',
      'Respecter les codes vestimentaires sur les îles habitées — bikinis autorisés uniquement sur les plages réservées aux touristes.',
      'Le snorkeling est souvent aussi spectaculaire que la plongée — et gratuit depuis la plage.',
      'Négocier les transferts en speed boat directement avec les hôtels — souvent inclus dans les packages.',
    ],
    tags: ['Lune de miel', 'Luxe', 'Plage', 'Snorkeling', 'Couple', 'Paradis'],
  },
  {
    slug: 'tunisie',
    name: 'Tunisie',
    continent: 'Afrique',
    coverImage: 'https://images.unsplash.com/photo-1539519532670-6a4e9eb65c13?w=1400&q=85',
    flagEmoji: '🇹🇳',
    halalScore: 4,
    capitalCity: 'Tunis',
    population: '12 millions',
    muslimPercentage: '99%',
    currency: 'Dinar tunisien (TND)',
    bestTime: 'Avril–juin · Septembre–novembre',
    shortDescription: 'La Méditerranée islamique — Carthage, Djerba, la médina de Tunis et une hospitalité légendaire.',
    description: 'La Tunisie est une destination halal magnifique et sous-estimée. À seulement 2h de vol de Paris, ce pays à majorité musulmane offre une combinaison unique : patrimoine punique et romain (Carthage, el-Jem), médinas islamiques classées UNESCO (Tunis, Kairouan, Sfax), plages turquoise et une gastronomie méditerranéenne authentiquement halal. Djerba, "l\'île aux mille et une nuits", est l\'une des destinations balnéaires halal les plus accessibles et les plus prisées des familles françaises.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste recommandée dans les médinas et sites religieux. Plus décontracté dans les zones touristiques.',
    mainCities: [
      { name: 'Tunis', slug: 'tunis', description: 'Capitale avec la médina classée UNESCO, souk de la Médina, musée du Bardo.' },
      { name: 'Djerba', slug: 'djerba', description: 'Île aux plages de sable blanc, architecture berbère et ambiance méditerranéenne unique.' },
      { name: 'Kairouan', slug: 'kairouan', description: 'Quatrième ville sainte de l\'islam, Grande Mosquée, médina et artisanat traditionnel.' },
      { name: 'Sousse', slug: 'sousse', description: 'Station balnéaire avec médina classée UNESCO, resorts et plages.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'vacances-halal-famille-2026', title: 'Vacances halal en famille : idées 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Faut-il un visa pour la Tunisie ?', answer: 'Non. Les ressortissants français, belges et suisses peuvent entrer en Tunisie sans visa pour un séjour touristique de moins de 3 mois avec un simple passeport ou une carte d\'identité.' },
      { question: 'La Tunisie est-elle sûre pour les touristes en 2026 ?', answer: 'Oui, les zones touristiques (Tunis, Djerba, Sousse, Hammamet) sont sûres. Le Ministère français des Affaires Étrangères recommande une vigilance normale dans ces zones.' },
      { question: 'Quel budget pour la Tunisie ?', answer: 'La Tunisie est très abordable. Repas locaux : 3-8€. Hôtel de qualité : 30-70€/nuit. Budget tout compris confortable : 50-90€/jour.' },
    ],
    tips: [
      'Le dinar tunisien ne peut pas être exporté — changer uniquement ce dont vous avez besoin.',
      'Le taxi partagé (louage) est le moyen de transport le plus pratique entre villes.',
      'Négocier est habituel dans les marchés et pour les excursions.',
      'Kairouan est une destination spirituelle majeure pour les musulmans — à ne pas manquer.',
      'Les resorts all-inclusive servent parfois de l\'alcool dans les buffets — vérifier avant de réserver.',
    ],
    tags: ['Méditerranée', 'Plage', 'Histoire', 'Culture', 'Famille', 'Budget'],
  },
  {
    slug: 'qatar',
    name: 'Qatar',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=1400&q=85',
    flagEmoji: '🇶🇦',
    halalScore: 5,
    capitalCity: 'Doha',
    population: '2.9 millions',
    muslimPercentage: '67%',
    currency: 'Riyal qatarien (QAR)',
    bestTime: 'Novembre–mars',
    shortDescription: 'Modernité ultracontemporaine et richesse islamique dans l\'un des États les plus riches du monde.',
    description: 'Le Qatar a émergé comme une destination touristique majeure depuis la Coupe du Monde 2022. Doha offre une skyline spectaculaire, des musées de classe mondiale (le Musée d\'Art Islamique est l\'un des plus beaux du monde), une gastronomie halal de qualité exceptionnelle et un accueil chaleureux. Petit État islamique mais ultra-moderne, le Qatar combine tradition bédouine (souk Waqif, désert de Khor Al Udaid) et contemporanéité absolue. La liaison Qatar Airways Paris–Doha est parmi les meilleures du monde.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Rare',
    dresscode: 'Tenue modeste dans les espaces publics. Respect des codes dans les mosquées et sites religieux.',
    mainCities: [
      { name: 'Doha', slug: 'doha', description: 'Capitale ultramoderne avec la corniche, le souk Waqif et des musées exceptionnels.' },
      { name: 'Al Wakrah', slug: 'al-wakrah', description: 'Ville côtière avec un souk traditionnel, moins touristique et plus authentique.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
    ],
    faqs: [
      { question: 'Faut-un visa pour le Qatar ?', answer: 'La plupart des ressortissants européens (dont les Français, Belges et Suisses) bénéficient d\'une entrée sans visa ou d\'un visa à l\'arrivée (gratuit, 30 jours). Vérifier sur le site de Qatar Airways.' },
      { question: 'Peut-on consommer de l\'alcool au Qatar ?', answer: 'L\'alcool est disponible dans les hôtels licenciés et certains restaurants, mais très facilement évitable. La grande majorité des restaurants qatariens n\'en servent pas.' },
    ],
    tips: [
      'Le souk Waqif à Doha est un incontournable pour l\'artisanat, les épices et l\'ambiance authentique.',
      'Le Musée d\'Art Islamique est une merveille architecturale — prévoir 2-3 heures.',
      'Le désert de Khor Al Udaid (dunes qui plongent dans la mer) est unique au monde.',
      'Qatar Airways propose souvent des escales à Doha incluses dans les billets longue distance — excellent moyen de visiter à moindre coût.',
    ],
    tags: ['Luxe', 'Culture', 'Moderne', 'Musées', 'Désert', 'Gastronomie'],
  },
  {
    slug: 'indonesie',
    name: 'Indonésie',
    continent: 'Asie du Sud-Est',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1400&q=85',
    flagEmoji: '🇮🇩',
    halalScore: 5,
    capitalCity: 'Jakarta',
    population: '277 millions',
    muslimPercentage: '87%',
    currency: 'Roupie indonésienne (IDR)',
    bestTime: 'Avril–octobre (saison sèche)',
    shortDescription: 'Plus grande population musulmane du monde — Bali halal, temples, rizières et volcans paradisiaques.',
    description: 'L\'Indonésie est le pays le plus peuplé du monde musulman, avec 240 millions de fidèles. Archipel de 17 000 îles, elle offre une diversité halal inégalée : Java et ses mosquées centenaires, Lombok (l\'île des mosquées), Banda Aceh (province islamique), sans oublier Bali — où les voyageurs musulmans bénéficient d\'une offre halal croissante dans un cadre paradisiaque. La gastronomie halal indonésienne (rendang, nasi goreng, satay) est l\'une des plus riches d\'Asie. L\'Indonésie est aussi l\'un des pays les plus abordables pour un voyage halal de qualité.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste dans les villes et sites islamiques. Plus de liberté dans les zones touristiques.',
    mainCities: [
      { name: 'Yogyakarta', slug: 'yogyakarta', description: 'Centre culturel de Java, temples de Borobudur, batik et gastronomie halal authentique.' },
      { name: 'Lombok', slug: 'lombok', description: 'L\'île des mosquées — alternative halal à Bali, plages immaculées et Mont Rinjani.' },
      { name: 'Banda Aceh', slug: 'banda-aceh', description: 'Capitale de la province islamique d\'Aceh, grande mosquée Baiturrahman, histoire et spiritualité.' },
      { name: 'Jakarta', slug: 'jakarta', description: 'Mégapole dynamique avec la Grande Mosquée Istiqlal, musées et gastronomie variée.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'vacances-halal-famille-2026', title: 'Vacances halal en famille : idées 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Bali est-elle une destination halal-friendly ?', answer: 'Oui, Bali accueille de nombreux voyageurs musulmans. Les restaurants halal se développent rapidement, notamment à Seminyak, Ubud et Kuta. Des zones résidentielles halal et des hôtels sans alcool existent. L\'île reste majoritairement hindoue mais s\'adapte très bien.' },
      { question: 'Faut-il un visa pour l\'Indonésie ?', answer: 'Les ressortissants français peuvent obtenir un visa à l\'arrivée (Visa on Arrival) pour 35$ valable 30 jours, prolongeable 30 jours supplémentaires. Un e-visa est également disponible en ligne avant le départ.' },
      { question: 'Quelle est la meilleure île pour un voyage halal en Indonésie ?', answer: 'Lombok est la destination halal par excellence — surnommée "l\'île aux mille mosquées". Les Gili Islands adjacentes proposent une offre balnéaire halal-friendly. Bali convient également avec une bonne préparation.' },
    ],
    tips: [
      'Grab est l\'application de transport de référence dans toutes les grandes villes.',
      'La devise locale doit être obtenue sur place — les taux de change sont bien meilleurs.',
      'Les appels à la prière sont très présents et marquent le rythme de vie — une expérience immersive.',
      'Lombok > Gili Trawangan pour une expérience plus halal-friendly en bord de mer.',
      'La cuisine de rue indonésienne est délicieuse et quasi-intégralement halal.',
    ],
    tags: ['Nature', 'Île', 'Gastronomie', 'Culture', 'Budget', 'Plage'],
  },
  {
    slug: 'bosnie-herzegovine',
    name: 'Bosnie-Herzégovine',
    continent: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=1400&q=85',
    flagEmoji: '🇧🇦',
    halalScore: 4,
    capitalCity: 'Sarajevo',
    population: '3.3 millions',
    muslimPercentage: '51%',
    currency: 'Mark convertible (BAM)',
    bestTime: 'Mai–septembre',
    shortDescription: 'La perle islamique d\'Europe — Sarajevo, Mostar et les paysages époustouflants des Balkans musulmans.',
    description: 'La Bosnie-Herzégovine est la destination halal européenne la plus authentique et la plus sous-estimée. Sarajevo, surnommée "la Jérusalem des Balkans", est l\'une des rares capitales européennes où l\'islam est majoritaire. L\'architecture ottomane, le Vieux Bazar Baščaršija, les mosquées centenaires et les cimetières de martyrs côtoient cafés et culture européenne moderne. Mostar et son pont emblématique, les cascades de Kravice, le lac de Jablanica — la nature bosnienne est d\'une beauté saisissante. Pour les Français musulmans, c\'est un voyage dépaysant à 2h d\'avion, sans choc culturel, avec une offre halal naturelle.',
    halalFoodAvailability: 'Bon',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue européenne normale. Tenue modeste dans les mosquées.',
    mainCities: [
      { name: 'Sarajevo', slug: 'sarajevo', description: 'Capitale islamique d\'Europe — mosquées ottomanes, Baščaršija, histoire et convivialité.' },
      { name: 'Mostar', slug: 'mostar', description: 'Le Vieux Pont classé UNESCO, architecture ottomane et atmosphère magique.' },
      { name: 'Travnik', slug: 'travnik', description: 'Ancienne capitale ottomane avec une forteresse médiévale et mosquées magnifiques.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'voyage-halal-debutant', title: 'Voyage halal pour débutants : guide complet', type: 'guide' },
    ],
    faqs: [
      { question: 'La Bosnie est-elle un pays sûr pour les touristes ?', answer: 'Oui, la Bosnie-Herzégovine est un pays sûr. Les incidents majeurs y sont très rares. Sarajevo est une ville accueillante et cosmopolite. À noter : des mines antipersonnel subsistent dans certaines zones rurales isolées hors des sentiers battus — rester sur les chemins balisés.' },
      { question: 'Faut-il un visa pour la Bosnie-Herzégovine ?', answer: 'Non, les ressortissants français, belges et suisses n\'ont pas besoin de visa pour la Bosnie-Herzégovine. Entrée libre avec passeport pour 90 jours.' },
      { question: 'La nourriture est-elle facilement halal à Sarajevo ?', answer: 'Oui. Sarajevo propose une excellente offre halal dans toute la ville. Le cevapi (brochettes), la pita bosnienne et les restaurants du Baščaršija sont quasiment tous halal. Les supermarchés affichent clairement les produits halal.' },
    ],
    tips: [
      'Le Sarajevo City Card offre des réductions dans de nombreux musées et transports.',
      'La cuisine bosnienne est exceptionnelle — ne pas manquer le cevapi et la pita fromage.',
      'Louer une voiture est recommandé pour explorer Mostar et les cascades de Kravice.',
      'Les taxis peuvent pratiquer des prix excessifs avec les touristes — négocier ou utiliser une application.',
      'Visiter le cimetière de Martyrs de Kovači — lieu de mémoire de la guerre de Bosnie (1992-1995).',
    ],
    tags: ['Europe', 'Histoire', 'Architecture ottomane', 'Nature', 'Gastronomie', 'Authentique'],
  },
  {
    slug: 'oman',
    name: 'Oman',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=1400&q=85',
    flagEmoji: '🇴🇲',
    halalScore: 5,
    capitalCity: 'Mascate',
    population: '4.5 millions',
    muslimPercentage: '86%',
    currency: 'Rial omanais (OMR)',
    bestTime: 'Octobre–mars',
    shortDescription: 'Le Moyen-Orient authentique et accueillant — wadis, désert, forts historiques et gastronomie halal.',
    description: 'Oman est le joyau méconnu du Moyen-Orient — une destination halal d\'une authenticité remarquable, bien loin de l\'ostentatoire de Dubai. Sultanat islamique ouvert et tolérant, Oman offre des paysages d\'une beauté sauvage : les wadis (oasis dans le désert), les dunes de sable rouge du désert du Wahiba, les fjords musandam, les forts historiques et les souks traditionnels. Mascate est une capitale paisible, propre et accueillante. La gastronomie omanaise halal mêle influences arabes, indiennes et africaines. Le pays est l\'un des plus sûrs du Moyen-Orient.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Rare',
    dresscode: 'Tenue modeste requise dans les espaces publics et les sites religieux. Dishdasha traditionnel courant.',
    mainCities: [
      { name: 'Mascate', slug: 'mascate', description: 'Capitale propre et accueillante avec la Grande Mosquée Sultan Qabous, souks et corniche.' },
      { name: 'Nizwa', slug: 'nizwa', description: 'Ancienne capitale, fort imposant, souk du vendredi aux chèvres, artisanat de l\'argent.' },
      { name: 'Salalah', slug: 'salalah', description: 'Ville verte unique en Arabie — saison des moussons (Khareef) spectaculaire.' },
      { name: 'Sur', slug: 'sur', description: 'Ville portuaire historique, dhows traditionnels et accès aux plages de tortues.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
    ],
    faqs: [
      { question: 'Faut-il un visa pour Oman ?', answer: 'Oui, les Français doivent obtenir un e-visa pour Oman (environ 20$, obtenu en ligne en 48h sur evisa.rop.gov.om). Valable 30 jours. Un visa à l\'arrivée est disponible dans certains aéroports.' },
      { question: 'Oman est-il une destination abordable ?', answer: 'Oman est moins onéreuse que Dubai ou le Qatar mais reste intermédiaire. Hébergement 50-120€/nuit, repas 5-20€. Budget confort : 100-150€/jour. Louer une voiture (35-60€/jour) est essentiel pour explorer le pays.' },
      { question: 'Peut-on faire du camping dans le désert à Oman ?', answer: 'Absolument, c\'est l\'une des expériences les plus belles du pays. Le désert du Wahiba Sands propose des campements permanents avec repas halal inclus. Le camping sauvage est également autorisé dans de nombreux wadis.' },
    ],
    tips: [
      'Louer une voiture 4x4 est indispensable pour explorer les wadis et le désert.',
      'L\'application Maps.me est utile car les GPS classiques manquent parfois les pistes de wadis.',
      'Visiter le souk de Nizwa le vendredi matin pour la vente de chèvres — expérience unique.',
      'Se baigner dans les wadis tôt le matin — fraîcheur et moins de monde.',
      'Le Ras Al Jinz Turtle Reserve (observation de tortues pondeuses) est une expérience inoubliable.',
    ],
    tags: ['Nature', 'Désert', 'Wadis', 'Authenticité', 'Histoire', 'Famille'],
  },
  {
    slug: 'zanzibar',
    name: 'Zanzibar (Tanzanie)',
    continent: 'Afrique',
    coverImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1400&q=85',
    flagEmoji: '🇹🇿',
    halalScore: 4,
    capitalCity: 'Stone Town',
    population: '1.9 millions',
    muslimPercentage: '99% (Zanzibar)',
    currency: 'Shilling tanzanien (TZS)',
    bestTime: 'Juin–octobre · Décembre–février',
    shortDescription: 'Plages paradisiaques, architecture swahili-arabe et tradition islamique dans l\'île aux épices.',
    description: 'Zanzibar est un archipel de rêve au large de la Tanzanie — et une destination halal naturelle exceptionnelle. Île à 99% musulmane, Zanzibar allie des plages de sable blanc parmi les plus belles du monde (Nungwi, Kendwa, Paje) à une culture swahili-arabo-islamique unique. Stone Town, classée UNESCO, est un labyrinthe de ruelles ornées de portes sculptées, de mosquées, de bazars épicés. La nourriture halal est omniprésente. Pour les familles et les couples français en quête d\'exotisme abordable, Zanzibar est une révélation.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste dans Stone Town et les villages locaux. Maillot de bain autorisé sur les plages touristiques.',
    mainCities: [
      { name: 'Stone Town', slug: 'stone-town', description: 'Ville historique classée UNESCO — architecture swahili-arabe, marchés et mosquées.' },
      { name: 'Nungwi', slug: 'nungwi', description: 'Village de pêcheurs au nord, plages de sable blanc, couchers de soleil spectaculaires.' },
      { name: 'Paje', slug: 'paje', description: 'Paradis du kitesurf, lagon peu profond et hôtels halal-friendly.' },
    ],
    relatedGuides: [
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Faut-il un visa pour Zanzibar ?', answer: 'Oui, les Français ont besoin d\'un visa pour la Tanzanie (dont fait partie Zanzibar). Il s\'obtient facilement en e-visa sur immigration.go.tz pour environ 50$. Valable 90 jours.' },
      { question: 'Zanzibar est-elle une destination sûre ?', answer: 'Oui, Zanzibar est considérée comme sûre pour les touristes. Respecter les codes vestimentaires locaux à Stone Town et dans les villages montre le respect des traditions et garantit un accueil chaleureux.' },
      { question: 'Quel budget pour Zanzibar ?', answer: 'Zanzibar est accessible. Guest houses locales : 30-60€/nuit. Hôtels intermédiaires : 60-120€/nuit. Resorts haut de gamme : 150-400€/nuit. Repas locaux : 3-8€. Budget confort : 80-120€/jour.' },
    ],
    tips: [
      'Couvrir épaules et jambes à Stone Town — c\'est une marque de respect très appréciée.',
      'Le forodhani gardens (marché de nuit de Stone Town) est le meilleur endroit pour manger halal à prix doux.',
      'Louer un scooter ou un taxi partagé (daladala) pour explorer l\'île à petit budget.',
      'Négocier les excursions sur place plutôt que depuis la France — prix 2 à 3 fois moins chers.',
      'Réserver la Spice Tour (tour des épices) pour comprendre l\'histoire arabo-swahili de l\'île.',
    ],
    tags: ['Plage', 'Île', 'Exotisme', 'Culture swahili', 'Couple', 'Budget'],
  },
  {
    slug: 'jordanie',
    name: 'Jordanie',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=1400&q=85',
    flagEmoji: '🇯🇴',
    halalScore: 5,
    capitalCity: 'Amman',
    population: '10 millions',
    muslimPercentage: '97%',
    currency: 'Dinar jordanien (JOD)',
    bestTime: 'Mars–mai · Septembre–novembre',
    shortDescription: 'Pétra, Wadi Rum et la Mer Morte dans un royaume islamique accueillant et sûr.',
    description: 'La Jordanie est une destination halal d\'exception combinant les plus grands sites archéologiques du Moyen-Orient et une atmosphère islamique sereine. Pétra, la cité nabatéenne sculptée dans le roc rose, est l\'une des sept merveilles du monde. Le Wadi Rum, désert de science-fiction aux dunes rouges, offre des bivouacs halal sous les étoiles. La Mer Morte, à -430m d\'altitude, et Aqaba sur la Mer Rouge complètent un tableau exceptionnel. La Jordanie est l\'un des pays les plus stables et les plus accueillants du Moyen-Orient.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste recommandée. Plus décontracté dans les zones touristiques et hôtels.',
    mainCities: [
      { name: 'Amman', slug: 'amman', description: 'Capitale moderne et historique — Citadelle, Temple d\'Hercule, gastronomie levantine.' },
      { name: 'Pétra', slug: 'petra', description: 'La cité rose nabatéenne, 7ème merveille du monde et site UNESCO incontournable.' },
      { name: 'Wadi Rum', slug: 'wadi-rum', description: 'Désert martien, bivouacs bédouins, dunes rouges et ciel étoilé exceptionnel.' },
      { name: 'Aqaba', slug: 'aqaba', description: 'Station balnéaire sur la Mer Rouge, plongée, plage et accès à la frontière d\'Israël.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
    ],
    faqs: [
      { question: 'Faut-il un visa pour la Jordanie ?', answer: 'Un visa à l\'arrivée (Jordan Pass inclus) est disponible pour environ 20 JOD (25€). Le Jordan Pass (40-80 JOD) combine visa + entrées dans plus de 40 sites dont Pétra — un excellent investissement pour les touristes.' },
      { question: 'La Jordanie est-elle sûre en 2026 ?', answer: 'Oui, la Jordanie est l\'un des pays les plus sûrs du Moyen-Orient. Pays neutre politiquement, il accueille des millions de touristes par an sans incident majeur. Les zones touristiques sont très sécurisées.' },
      { question: 'Combien de jours pour visiter Pétra ?', answer: 'Minimum 2 jours pour Pétra seule. Un day-trip depuis Amman est possible mais épuisant. Dormir à Wadi Musa (village adjacent) permet d\'arriver tôt à l\'ouverture et d\'éviter les horaires d\'affluence maximale.' },
    ],
    tips: [
      'Le Jordan Pass est presque toujours rentable si vous prévoyez de visiter Pétra.',
      'Wadi Rum se visite idéalement en 2 jours avec un bivouac bédouin inclus.',
      'La Mer Morte est à 1h d\'Amman — une matinée suffit pour en profiter.',
      'Le mansaf (agneau et riz au yaourt fermenté) est le plat national — à goûter absolument.',
      'Uber Jordanie est disponible et fiable — meilleur que les taxis non comptés.',
    ],
    tags: ['Histoire', 'Archéologie', 'Désert', 'Nature', 'Culture', 'Pétra'],
  },
  {
    slug: 'albanie',
    name: 'Albanie',
    continent: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1597655601841-214a4cfe8b2c?w=1400&q=85',
    flagEmoji: '🇦🇱',
    halalScore: 3,
    capitalCity: 'Tirana',
    population: '2.8 millions',
    muslimPercentage: '58%',
    currency: 'Lek albanais (ALL)',
    bestTime: 'Mai–septembre',
    shortDescription: 'La pépite secrète d\'Europe — côte ionienne, cuisine halal surprenante et authenticité balkanique.',
    description: 'L\'Albanie est la destination européenne la plus confidentielle et la plus prometteuse pour les voyageurs halal. À majorité musulmane (58%), elle offre une cuisine facilement halal (viande d\'agneau et de bœuf omniprésente), des mosquées dans toutes les villes et une hospitalité balkanique incomparable. La côte ionienne albanaise est souvent comparée aux Côtes grecques des années 1980 : eau cristalline, villages de pêcheurs intacts et prix 3 à 5 fois inférieurs. Tirana, capitale dynamique et colorée, Gjirokastër classée UNESCO, le lac d\'Ohrid — l\'Albanie surprend et enchante.',
    halalFoodAvailability: 'Bon',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue européenne normale. Modestie respectée dans les mosquées.',
    mainCities: [
      { name: 'Tirana', slug: 'tirana', description: 'Capitale colorée et dynamique — Et\'hem Bey Mosque, Blloku, vie nocturne animée.' },
      { name: 'Gjirokastër', slug: 'gjirokaster', description: 'Ville-musée classée UNESCO avec château ottoman et maisons en pierre authentiques.' },
      { name: 'Sarandë', slug: 'sarande', description: 'Riviera albanaise face à Corfou — eaux turquoise, plages de galets, ambiance décontractée.' },
      { name: 'Berat', slug: 'berat', description: 'La ville aux mille fenêtres, classée UNESCO, avec son château ottoman.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'voyage-halal-debutant', title: 'Voyage halal pour débutants : guide complet', type: 'guide' },
    ],
    faqs: [
      { question: 'La nourriture est-elle facilement halal en Albanie ?', answer: 'Globalement oui. La viande d\'agneau et de bœuf, piliers de la cuisine albanaise, est naturellement halal dans la plupart des boucheries et restaurants. Dans les grandes villes, des restaurants certifiés halal existent. Dans les zones touristiques, demander confirmation reste conseillé.' },
      { question: 'Faut-il un visa pour l\'Albanie ?', answer: 'Non. Les ressortissants français, belges et suisses peuvent entrer en Albanie sans visa pour un séjour de moins de 90 jours. L\'Albanie ne fait pas partie de l\'UE mais est candidate à l\'adhésion.' },
      { question: 'Comment se déplacer en Albanie ?', answer: 'Les minibus (furgon) sont le moyen de transport local le plus utilisé entre villes. Uber n\'est pas disponible mais Bolt fonctionne à Tirana. Louer une voiture reste la meilleure option pour explorer la côte et l\'intérieur.' },
    ],
    tips: [
      'Changer des euros en leks directement dans les bureaux de change en ville — meilleurs taux.',
      'La côte ionienne (Dhermi, Himara) est magnifique mais les routes de montagne d\'accès sont sinueuses.',
      'La qofte (galettes d\'agneau grillées) et le tave kosi (agneau au yaourt) sont les plats incontournables.',
      'L\'Albanie est l\'un des pays les moins chers d\'Europe — budget très accessible.',
      'Visiter le Bunk\'Art (anciens bunkers reconvertis en musée) à Tirana pour comprendre l\'histoire communiste.',
    ],
    tags: ['Europe', 'Budget', 'Côte', 'Authenticité', 'Nature', 'Découverte'],
  },
  {
    slug: 'japon',
    name: 'Japon',
    continent: 'Asie',
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1400&q=85',
    flagEmoji: '🇯🇵',
    halalScore: 3,
    capitalCity: 'Tokyo',
    population: '125 millions',
    muslimPercentage: '0.2%',
    currency: 'Yen japonais (JPY)',
    bestTime: 'Mars–mai · Octobre–novembre',
    shortDescription: 'Le Japon halal est possible — mosquées à Tokyo, restaurants certifiés et aventure culturelle unique.',
    description: 'Le Japon est une destination atypique pour les voyageurs halal — non islamique, mais de plus en plus adapté. Avec une communauté musulmane croissante et un gouvernement actif dans le tourisme halal, les options se multiplient : restaurants certifiés halal à Tokyo, Osaka et Kyoto, mosquées dans les grandes villes, guides touristiques dédiés aux musulmans. Le Japon offre une expérience culturelle incomparable : temples bouddhistes et shinto, cerisiers en fleur, gastronomie (sushi, ramen adaptés), animés, ryokan (auberges traditionnelles) et politesse légendaire. Un défi qui en vaut la peine pour les voyageurs aventureux.',
    halalFoodAvailability: 'Moyen',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Très présent',
    dresscode: 'Tenue adaptée aux saisons. Modestie dans les temples et lieux sacrés.',
    mainCities: [
      { name: 'Tokyo', slug: 'tokyo', description: 'Mégapole futuriste avec la Tokyo Camii (plus grande mosquée), quartiers halal à Shinjuku.' },
      { name: 'Osaka', slug: 'osaka', description: 'Capitale gastronomique du Japon avec des restaurants halal croissants et Dotonbori animé.' },
      { name: 'Kyoto', slug: 'kyoto', description: 'Temples dorés, geishas, jardins zen — quintessence du Japon traditionnel.' },
      { name: 'Hiroshima', slug: 'hiroshima', description: 'Ville symbole de paix, mémorial, île de Miyajima et torii dans la mer.' },
    ],
    relatedGuides: [
      { slug: 'checklist-voyage-halal', title: 'Checklist voyage halal : ne rien oublier', type: 'guide' },
      { slug: 'trouver-mosquee-en-voyage', title: 'Comment trouver une mosquée en voyage', type: 'guide' },
    ],
    faqs: [
      { question: 'Comment trouver des restaurants halal au Japon ?', answer: 'L\'application Halal Navi et le site HalalMedia.jp répertorient les restaurants certifiés halal. Dans les supermarchés, chercher les logos halal en arabe. Les restaurants indiens, turcs et malaisiens au Japon sont généralement halal. Le végétarien/vegan est une bonne alternative.' },
      { question: 'Y a-t-il des mosquées au Japon ?', answer: 'Oui, environ 100 mosquées au Japon. La plus grande est la Tokyo Camii à Yoyogi (turque, magnifique). À Osaka : Islamic Cultural Center, Masjid Al-Noor. Des salles de prière existent dans certains aéroports et centres commerciaux.' },
      { question: 'Le Japon est-il accessible pour les voyageurs halal solitaires ?', answer: 'Avec de la préparation, oui. Télécharger Halal Navi avant le départ, repérer les mosquées, opter pour des cuisines internationales halal (indien, turc, malais) et profiter de la culture unique font du Japon une aventure inoubliable malgré les défis alimentaires.' },
    ],
    tips: [
      'Télécharger Halal Navi et Muslim Pro avant le départ pour localiser restaurants et mosquées.',
      'Le JR Pass (à acheter avant le départ en France) est rentable pour voyager en Shinkansen.',
      'Les 7-Eleven et FamilyMart proposent de plus en plus d\'options halal certifiées.',
      'Réserver des ryokan (auberges) avec option végétarienne facilite le halal.',
      'Le Ramadan au Japon est discret — plusieurs mosquées organisent des iftars communautaires.',
    ],
    tags: ['Aventure', 'Culture', 'Technologie', 'Gastronomie', 'Nature', 'Unique'],
  },
  {
    slug: 'thaïlande',
    name: 'Thaïlande',
    continent: 'Asie du Sud-Est',
    coverImage: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1400&q=85',
    flagEmoji: '🇹🇭',
    halalScore: 3,
    capitalCity: 'Bangkok',
    population: '72 millions',
    muslimPercentage: '5%',
    currency: 'Baht thaïlandais (THB)',
    bestTime: 'Novembre–mars (saison sèche)',
    shortDescription: 'Temples dorés, plages paradisiaques et halal surprenant à Bangkok et dans le Sud thaïlandais.',
    description: 'La Thaïlande n\'est pas une destination islamique mais elle s\'adapte de mieux en mieux aux voyageurs halal. Bangkok compte des centaines de restaurants halal certifiés (quartier arabe de Sukhumvit, Chinatown halal), des mosquées dans tous les quartiers et un quartier musulman à Haroon. Le sud thaïlandais — Krabi, Koh Lanta, Had Yai — est à majorité musulmane (provinces de Pattani, Yala, Narathiwat) avec une offre halal naturelle. Les plages de Koh Lanta et Krabi séduisent par leur beauté sans équivalent à prix raisonnables.',
    halalFoodAvailability: 'Bon',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Très présent',
    dresscode: 'Tenue adaptée. Modestie dans les temples. Couvrir épaules et genoux dans les sites bouddhistes.',
    mainCities: [
      { name: 'Bangkok', slug: 'bangkok', description: 'Capitale trépidante avec quartier arabe halal, mosquées et temples d\'or spectaculaires.' },
      { name: 'Krabi', slug: 'krabi', description: 'Falaises calcaires, plages turquoise, mer d\'Andaman et options halal dans le Sud.' },
      { name: 'Koh Lanta', slug: 'koh-lanta', description: 'Île à majorité musulmane, plages préservées, village de pêcheurs authentique.' },
      { name: 'Chiang Mai', slug: 'chiang-mai', description: 'Capitale du Nord, temples, éléphants, marchés nocturnes et restaurants halal.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'checklist-voyage-halal', title: 'Checklist voyage halal : ne rien oublier', type: 'guide' },
    ],
    faqs: [
      { question: 'Koh Lanta est-elle une bonne destination halal ?', answer: 'Oui, Koh Lanta est l\'île thaïlandaise la plus halal-friendly. À majorité musulmane malaise, les restaurants halal sont majoritaires dans les villages locaux. Les plages de Long Beach et Klong Dao sont magnifiques sans excès alcoolisés.' },
      { question: 'Y a-t-il des mosquées à Bangkok ?', answer: 'Oui, Bangkok compte plus de 170 mosquées. La grande mosquée Haroon (Khlong San), Masjid Makkah (Sukhumvit) et la mosquée de Chinatown sont les plus connues. L\'application Muslim Pro localise toutes les mosquées en temps réel.' },
      { question: 'La nourriture thaïlandaise est-elle facilement halal ?', answer: 'Cela dépend des zones. Dans les provinces du Sud et les quartiers arabes de Bangkok, tout est halal. Dans les zones touristiques nord (Chiang Mai, Phuket), une sélection plus soigneuse est nécessaire. Les restaurants végétariens et indiens sont de bonnes alternatives.' },
    ],
    tips: [
      'Grab est l\'application de transport officielle — indispensable à Bangkok et dans les grandes villes.',
      'Le quartier Sukhumvit Soi 3 à Bangkok est le "quartier arabe" — restaurants halal excellents.',
      'Koh Lanta en novembre-mars : paradis halal de la mer d\'Andaman.',
      'L\'eau de noix de coco fraîche est la boisson parfaite — disponible partout.',
      'Koh Samui est moins halal-friendly — préférer Koh Lanta ou Krabi pour les familles.',
    ],
    tags: ['Plage', 'Culture', 'Nature', 'Gastronomie', 'Budget', 'Famille'],
  },
  {
    slug: 'france',
    name: 'France',
    continent: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1400&q=85',
    flagEmoji: '🇫🇷',
    halalScore: 3,
    capitalCity: 'Paris',
    population: '68 millions',
    muslimPercentage: '8-10%',
    currency: 'Euro (EUR)',
    bestTime: 'Avril–juin · Septembre–octobre',
    shortDescription: 'La France halal révélée — de Paris à Marseille, une offre halal foisonnante à découvrir.',
    description: 'La France est la première communauté musulmane d\'Europe avec 5 à 6 millions de fidèles — et une offre halal exceptionnellement développée. Paris compte plus de 1 500 restaurants halal certifiés, des mosquées dans tous les arrondissements et un vivier culinaire halal extraordinaire (shawarma, cuisines maghrébines, turques, africaines). Mais au-delà de Paris, c\'est toute la France qui se révèle : Lyon capitale gastronomique avec ses bouchons halal, Marseille et sa biodiversité culinaire halal incomparable, Toulouse, Bordeaux, Strasbourg. Pour les voyageurs musulmans francophones du monde entier, la France est une découverte.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Très présent',
    dresscode: 'Tenue libre. Le voile est autorisé dans la rue et dans tous les espaces publics.',
    mainCities: [
      { name: 'Paris', slug: 'paris', description: 'Capitale mondiale halal — 1 500 restaurants, Grande Mosquée, art et culture incomparables.' },
      { name: 'Marseille', slug: 'marseille', description: 'Capitale culinaire halal de France — diversité méditerranéenne et communautés du monde entier.' },
      { name: 'Lyon', slug: 'lyon', description: 'Capitale gastronomique avec une scène halal en pleine expansion.' },
      { name: 'Strasbourg', slug: 'strasbourg', description: 'Alsace alsacienne et Grande Mosquée de France, architecture médiévale unique.' },
    ],
    relatedGuides: [
      { slug: 'voyage-halal-debutant', title: 'Voyage halal pour débutants : guide complet', type: 'guide' },
      { slug: 'trouver-mosquee-en-voyage', title: 'Comment trouver une mosquée en voyage', type: 'guide' },
    ],
    faqs: [
      { question: 'Y a-t-il beaucoup de restaurants halal à Paris ?', answer: 'Paris est l\'une des capitales mondiales du halal avec plus de 1 500 restaurants certifiés. Les quartiers les plus riches en offre halal : Barbès (18e), Belleville (20e/19e), Château Rouge, La Chapelle. Mais le halal s\'est démocratisé dans tous les arrondissements.' },
      { question: 'Le port du voile est-il autorisé en France ?', answer: 'Oui, le voile est autorisé dans la rue, les commerces, les espaces publics et la plupart des lieux de travail privés. Il est interdit dans les écoles publiques, lycées, fonctions publiques et espaces officiels de l\'État. La abaya a été interdite dans les écoles publiques depuis 2023.' },
      { question: 'Quelles grandes mosquées visiter en France ?', answer: 'La Grande Mosquée de Paris (5e arrondissement, 1926) est la plus emblématique. Celle de Lyon, Strasbourg, Évry, Mantes-la-Jolie sont parmi les plus belles. Marseille dispose de nombreuses mosquées dans ses quartiers nord.' },
    ],
    tips: [
      'L\'application Halal Squad et Zabihah.com répertorient les restaurants halal certifiés partout en France.',
      'Paris : les quartiers de Barbès, Belleville et La Chapelle offrent l\'offre halal la plus dense et la moins chère.',
      'La Grande Mosquée de Paris propose un salon de thé et un restaurant — une expérience incontournable.',
      'En province, les grandes villes ont toutes des mosquées et des bouchers halal — utiliser Maps pour localiser.',
      'Les chaînes O\'Tacos, Bun Bun Burger et Tacos de Lyon ont des enseignes halal certifiées.',
    ],
    tags: ['Europe', 'Culture', 'Gastronomie', 'Art', 'Histoire', 'Famille'],
  },
  {
    slug: 'royaume-uni',
    name: 'Royaume-Uni',
    continent: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1400&q=85',
    flagEmoji: '🇬🇧',
    halalScore: 4,
    capitalCity: 'Londres',
    population: '68 millions',
    muslimPercentage: '6.5%',
    currency: 'Livre sterling (GBP)',
    bestTime: 'Mai–septembre',
    shortDescription: 'Londres halal capitale — Brick Lane, mosquées centenaires et une scène culinaire halal parmi les meilleures d\'Europe.',
    description: 'Le Royaume-Uni abrite la plus importante communauté musulmane de l\'Europe anglophone avec 3,9 millions de fidèles. Londres est un paradis halal : Brick Lane (quartier bangladeshi), Edgware Road (quartier arabe londonien), East London, Whitechapel — des centaines de restaurants halal de toutes cuisines, des mosquées majestuelles (London Central Mosque de Regent\'s Park, East London Mosque). Au-delà de Londres, Birmingham, Manchester, Bradford et Leicester ont des communautés musulmanes importantes avec une infrastructure halal complète. Le Royaume-Uni est aussi une destination touristique de premier plan : Big Ben, Tower Bridge, Oxford, Édimbourg.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Très présent',
    dresscode: 'Tenue libre. Le hijab et la abaya sont pleinement acceptés et portés librement.',
    mainCities: [
      { name: 'Londres', slug: 'londres', description: 'Capitale mondiale du halal en Europe — Brick Lane, Edgware Road, East End.' },
      { name: 'Birmingham', slug: 'birmingham', description: 'Deuxième ville du pays, communauté musulmane importante, Balti Triangle (cuisine pakistanaise).' },
      { name: 'Manchester', slug: 'manchester', description: 'Curry Mile de Rusholme, football, architecture victorienne et scène halal animée.' },
      { name: 'Édimbourg', slug: 'edinburgh', description: 'Capitale écossaise avec château médiéval, whisky (évitable) et mosquée centrale.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'voyage-halal-debutant', title: 'Voyage halal pour débutants : guide complet', type: 'guide' },
    ],
    faqs: [
      { question: 'Le Royaume-Uni nécessite-t-il un visa pour les Français ?', answer: 'Depuis le Brexit, les ressortissants français doivent obtenir une ETA (Electronic Travel Authorisation) pour visiter le Royaume-Uni — environ 10£, demandée en ligne sur gov.uk/etatourist. Le passeport est obligatoire (la carte d\'identité n\'est plus acceptée depuis 2021).' },
      { question: 'Quels sont les meilleurs quartiers halal de Londres ?', answer: 'Brick Lane (E1, cuisine bangladeshi-indienne halal), Edgware Road (cuisine arabe levantine), Whitechapel (Bangladesh Town, mosquée East London), Tooting (cuisine pakistanaise/indienne), Shepherd\'s Bush (cuisine africaine/maghrébine) sont les plus célèbres.' },
      { question: 'Quel budget pour Londres ?', answer: 'Londres est l\'une des capitales les plus chères d\'Europe. Hôtel 3* : 100-180£/nuit. Repas halal : 8-20£. Transport Oyster Card : 2-3£ par trajet. Budget quotidien confort : 150-250£. Les musées (British Museum, V&A, Natural History) sont gratuits.' },
    ],
    tips: [
      'L\'Oyster Card (carte de transport rechargeable) est indispensable à Londres.',
      'Brick Lane le dimanche matin — marché, bagels et énergie multiculturelle unique.',
      'Les musées londoniens majeurs sont gratuits — une économie considérable.',
      'Airbnb avec cuisine est plus économique que les hôtels pour les familles.',
      'L\'ETA (Electronic Travel Authorisation) est obligatoire depuis 2024 — demander avant le départ.',
    ],
    tags: ['Europe', 'Culture', 'Gastronomie', 'Histoire', 'Shopping', 'Famille'],
  },
]

export function getCountryBySlug(slug: string): Country | undefined {
  return countries.find((c) => c.slug === slug)
}
