export interface Country {
  slug: string
  name: string
  continent: string
  coverImage: string
  flagEmoji: string
  halalScore: number
  capitalCity: string
  population: string
  muslimPercentage: string
  currency: string
  bestTime: string
  description: string
  shortDescription: string
  halalFoodAvailability: 'Excellent' | 'Bon' | 'Moyen' | 'Difficile'
  mosquesPresence: 'Partout' | 'Dans les villes' | 'Rares'
  alcoholPolicy: 'Interdit' | 'Rare' | 'Disponible mais évitable' | 'Très présent'
  dresscode: string
  mainCities: { name: string; slug: string; description: string }[]
  relatedGuides: { slug: string; title: string; type: 'guide' | 'blog' }[]
  faqs: { question: string; answer: string }[]
  tips: string[]
  tags: string[]
}

export const countries: Country[] = [
  {
    slug: 'turquie',
    name: 'Turquie',
    continent: 'Europe / Asie',
    coverImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1400&q=85',
    flagEmoji: '🇹🇷',
    halalScore: 5,
    capitalCity: 'Ankara',
    population: '85 millions',
    muslimPercentage: '99%',
    currency: 'Lire turque (TRY)',
    bestTime: 'Avril–juin · Septembre–novembre',
    shortDescription: 'L\'empire ottoman revit à travers ses mosquées millénaires et sa gastronomie 100% halal.',
    description: 'La Turquie est incontestablement la destination halal reine pour les voyageurs musulmans francophones. Pays à 99% musulman, elle offre une liberté totale : nourriture halal partout, mosquées à chaque coin de rue, appel à la prière cinq fois par jour. D\'Istanbul à la Cappadoce, de la côte égéenne aux monts du Taurus, la Turquie est une mosaïque de civilisations islamiques, de paysages époustouflants et d\'une gastronomie d\'une richesse incomparable. Accessible en vol direct depuis Paris (3h30), abordable, sécurisée et accueillante — elle cumule tous les avantages pour un voyage halal parfait.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste recommandée dans les mosquées et quartiers conservateurs. Couverture des épaules et des genoux obligatoire pour visiter les mosquées.',
    mainCities: [
      { name: 'Istanbul', slug: 'istanbul', description: 'La perle du Bosphore, entre Europe et Asie, 3 000 mosquées, gastronomie halal incomparable.' },
      { name: 'Cappadoce', slug: 'cappadoce', description: 'Paysages lunaires, montgolfières et cave-hôtels. L\'expérience la plus unique de Turquie.' },
      { name: 'Antalya', slug: 'antalya', description: 'La riviera turque — plages immaculées, resorts halal et histoire antique.' },
      { name: 'Bursa', slug: 'bursa', description: 'Première capitale ottomane, grande mosquée, marché couvert et bains thermaux.' },
    ],
    relatedGuides: [
      { slug: 'istanbul-guide-halal-complet', title: 'Istanbul halal : guide complet 2026', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
    ],
    faqs: [
      { question: 'La nourriture est-elle entièrement halal en Turquie ?', answer: 'Oui, à 99%. La quasi-totalité des restaurants en Turquie servent de la viande halal par défaut, notamment dans les quartiers traditionnels. Dans les zones très touristiques ou les établissements internationaux, une certification halal peut être demandée.' },
      { question: 'Peut-on trouver de l\'alcool en Turquie ?', answer: 'L\'alcool est légal en Turquie mais facilement évitable. Dans les quartiers conservateurs et la plupart des restaurants traditionnels, aucun alcool n\'est servi. Evitez simplement les bars et restaurants de type occidental dans les zones touristiques.' },
      { question: 'Quelles mosquées visiter absolument en Turquie ?', answer: 'La Mosquée Bleue et Sainte-Sophie à Istanbul sont incontournables. La Grande Mosquée de Bursa (Ulu Camii), la Mosquée Selimiye à Edirne (classée UNESCO) et la Mosquée Hacı Bayram à Ankara complètent le tableau.' },
      { question: 'Quel est le meilleur moment pour visiter la Turquie ?', answer: 'Avril-juin et septembre-novembre offrent les meilleures conditions : températures agréables (20-28°C), moins de touristes. Juillet-août est la haute saison balnéaire (chaud, bondé). Décembre-février est idéal pour visiter Istanbul et la Cappadoce sous la neige.' },
    ],
    tips: [
      'La carte Istanbulkart est indispensable pour les transports en commun à Istanbul.',
      'Negocier est une pratique normale dans les bazars — commencez à 50% du prix affiché.',
      'Le hamam est une expérience culturelle incontournable — choisir un établissement traditionnel dans les vieux quartiers.',
      'Les restaurants autour des grandes mosquées touristiques pratiquent souvent des prix majorés — s\'éloigner d\'une rue ou deux.',
      'Le visa e-Visa est obtenu en quelques minutes sur evisa.gov.tr pour les ressortissants français.',
    ],
    tags: ['Culture ottomane', 'Gastronomie', 'Histoire', 'Architecture', 'Mer', 'Montagne'],
  },
  {
    slug: 'maroc',
    name: 'Maroc',
    continent: 'Afrique',
    coverImage: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=1400&q=85',
    flagEmoji: '🇲🇦',
    halalScore: 5,
    capitalCity: 'Rabat',
    population: '37 millions',
    muslimPercentage: '99%',
    currency: 'Dirham marocain (MAD)',
    bestTime: 'Mars–mai · Septembre–novembre',
    shortDescription: 'Pays halal par nature, le Maroc offre médinas, riads et gastronomie dans un écrin islamique authentique.',
    description: 'Le Maroc est la destination halal la plus prisée des Français musulmans — et pour cause. À 2h30 de vol de Paris, ce pays à 99% musulman propose un voyage sans aucun compromis : nourriture halal dans chaque restaurant, rythme de vie islamique naturel, architecture arabo-andalouse magnifique et accueil chaleureux. Marrakech, Fès, Chefchaouen, les dunes du Sahara — chaque recoin du Maroc est une carte postale. Pour les familles, les couples et les voyageurs solo, le Maroc répond à toutes les attentes.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Rare',
    dresscode: 'Tenue modeste respectée dans les médinas et les mosquées. Les femmes voilées sont pleinement respectées.',
    mainCities: [
      { name: 'Marrakech', slug: 'marrakech', description: 'La ville ocre et ses souks mythiques, riads somptueux et place Jemaa el-Fna.' },
      { name: 'Fès', slug: 'fes', description: 'La médina de Fès, classée UNESCO, est l\'une des vieilles villes islamiques les mieux préservées au monde.' },
      { name: 'Chefchaouen', slug: 'chefchaouen', description: 'La ville bleue nichée dans le Rif, joyau photographique du Maroc.' },
      { name: 'Essaouira', slug: 'essaouira', description: 'Cité des alizés, architecture blanche et bleue, ambiance détendue en bord de mer.' },
    ],
    relatedGuides: [
      { slug: 'marrakech-guide-halal', title: 'Marrakech halal : guide complet 2026', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Tout est-il halal au Maroc ?', answer: 'Oui, quasi intégralement. Le Maroc étant un État islamique, la totalité des restaurants, boucheries et établissements alimentaires respectent les préceptes halal par défaut. Aucune vérification n\'est nécessaire.' },
      { question: 'Quelle est la meilleure période pour visiter le Maroc ?', answer: 'Mars à mai et septembre à novembre sont idéaux : températures de 20-25°C, ciel bleu, moins de touristes. Juillet-août est très chaud (40°C+ dans l\'intérieur), décembre-février est doux et agréable.' },
      { question: 'Quel budget prévoir pour un voyage au Maroc ?', answer: 'Le Maroc est très abordable. Un riad de standing moyen à Marrakech coûte 50-80€/nuit, les restaurants locaux de 3 à 8€. Budget tout compris : 60-150€/jour selon le confort souhaité.' },
      { question: 'Faut-il un visa pour le Maroc ?', answer: 'Non, les ressortissants français, belges et suisses n\'ont pas besoin de visa pour le Maroc. Un séjour de moins de 90 jours est libre avec passeport ou carte d\'identité.' },
    ],
    tips: [
      'Négocier est culturellement attendu dans tous les souks — ne jamais payer le premier prix.',
      'Se méfier des "guides" non officiels aux abords des médinas — opter pour une agence locale agréée.',
      'Les riads de la médina offrent l\'expérience la plus authentique et sont souvent moins chers que les hôtels de chaîne.',
      'L\'eau du robinet n\'est pas recommandée — boire uniquement de l\'eau en bouteille.',
      'Le dirham marocain ne peut pas être sorti du territoire — changer uniquement ce dont vous avez besoin.',
    ],
    tags: ['Médina', 'Souks', 'Désert', 'Gastronomie', 'Architecture', 'Plage'],
  },
  {
    slug: 'emirats-arabes-unis',
    name: 'Émirats Arabes Unis',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1400&q=85',
    flagEmoji: '🇦🇪',
    halalScore: 5,
    capitalCity: 'Abu Dhabi',
    population: '10 millions',
    muslimPercentage: '76% (résidents)',
    currency: 'Dirham des EAU (AED)',
    bestTime: 'Novembre–avril',
    shortDescription: 'Modernité absolue et luxe halal garanti dans le cadre d\'un État islamique ultra-développé.',
    description: 'Les Émirats Arabes Unis représentent le summum du tourisme halal contemporain. État islamique à 100%, la certification halal y est obligatoire pour tous les établissements de restauration — une garantie unique au monde. Dubai et Abu Dhabi combinent des gratte-ciels futuristes, des plages de sable blanc, le shopping de luxe, des musées de classe mondiale et une infrastructure hôtelière 5 étoiles dans un cadre entièrement conforme aux valeurs islamiques. Une destination idéale pour les familles aisées et les voyageurs exigeants.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue correcte dans les espaces publics et centres commerciaux. Tenues de plage réservées aux zones balnéaires.',
    mainCities: [
      { name: 'Dubaï', slug: 'dubai', description: 'La ville la plus spectaculaire du monde — Burj Khalifa, Palm Jumeirah, shopping de luxe.' },
      { name: 'Abu Dhabi', slug: 'abu-dhabi', description: 'Capitale et siège de la Grande Mosquée Sheikh Zayed, l\'une des plus belles du monde.' },
      { name: 'Sharjah', slug: 'sharjah', description: 'L\'Émirat culturel, plus conservateur, avec d\'excellents musées islamiques.' },
    ],
    relatedGuides: [
      { slug: 'dubai-guide-halal-2026', title: 'Dubai halal : guide complet 2026', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : destinations romantiques', type: 'guide' },
    ],
    faqs: [
      { question: 'La nourriture est-elle garantie halal aux EAU ?', answer: 'Oui, par obligation légale. Tous les restaurants des EAU doivent obtenir une certification halal pour opérer. Vous pouvez manger en toute confiance dans n\'importe quel établissement.' },
      { question: 'Quel est le meilleur moment pour visiter Dubai ?', answer: 'Novembre à avril est la saison idéale avec des températures de 20-28°C. Juillet-août est extrêmement chaud (45°C+) mais les prix des hôtels chutent drastiquement.' },
      { question: 'Quel budget prévoir pour Dubai ?', answer: 'Dubai peut être abordable ou luxueux selon vos choix. Budget "confort" : 150-250€/jour. Budget "luxe" : 400€+/jour. Les centres commerciaux, plages publiques et certaines activités sont gratuits ou peu coûteux.' },
      { question: 'Y a-t-il des plages séparées pour hommes et femmes à Dubai ?', answer: 'Certaines plages et piscines d\'hôtels proposent des créneaux séparés sur demande. La plupart des hôtels 5 étoiles ont des options adaptées aux familles conservatrices.' },
    ],
    tips: [
      'Le Dubai Mall et les transports en commun (Metro) sont excellents et très économiques.',
      'Uber et Careem sont fiables et moins chers que les taxis traditionnels.',
      'Eviter les taxis non officiels à la sortie des aéroports.',
      'La Mosquée Jumeirah est ouverte aux non-musulmans avec visites guidées — à ne pas manquer.',
      'Les activités en famille comme le parc aquatique Atlantis ou le désert peuvent être réservées à l\'avance avec des réductions significatives.',
    ],
    tags: ['Luxe', 'Shopping', 'Architecture', 'Désert', 'Plage', 'Famille'],
  },
  {
    slug: 'malaisie',
    name: 'Malaisie',
    continent: 'Asie du Sud-Est',
    coverImage: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1400&q=85',
    flagEmoji: '🇲🇾',
    halalScore: 5,
    capitalCity: 'Kuala Lumpur',
    population: '33 millions',
    muslimPercentage: '63%',
    currency: 'Ringgit malaisien (MYR)',
    bestTime: 'Toute l\'année (éviter mousson mai–octobre)',
    shortDescription: 'N°1 mondial du tourisme halal — certification JAKIM, gastronomie fusion et modernité incomparables.',
    description: 'La Malaisie est régulièrement couronnée meilleure destination halal mondiale par le Global Muslim Travel Index. Et pour cause : le système de certification JAKIM (Département des affaires islamiques de Malaisie) est le plus rigoureux au monde. Chaque restaurant, hôtel et produit alimentaire doit renouveler annuellement sa certification. Pour le voyageur musulman, c\'est une liberté totale et une tranquillité d\'esprit absolue. Kuala Lumpur combine la modernité des tours Petronas, une gastronomie halal fusion extraordinaire (influences malaise, chinoise et indienne) et des prix très inférieurs à l\'Europe.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste respectueuse dans les mosquées et zones rurales. Plus décontracté dans les quartiers urbains modernes.',
    mainCities: [
      { name: 'Kuala Lumpur', slug: 'kuala-lumpur', description: 'La capitale halal du monde — tours Petronas, food courts certifiés, vie nocturne islamique.' },
      { name: 'Penang', slug: 'penang', description: 'Île patrimoniale UNESCO avec une scène gastronomique halal exceptionnelle.' },
      { name: 'Malacca', slug: 'malacca', description: 'Port historique classé UNESCO, carrefour des civilisations islamo-malaise.' },
      { name: 'Langkawi', slug: 'langkawi', description: 'Archipel tropical paradisiaque avec des hôtels halal de luxe.' },
    ],
    relatedGuides: [
      { slug: 'malaisie-halal-destination', title: 'Malaisie : la destination n°1 mondiale pour les musulmans', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
    ],
    faqs: [
      { question: 'Qu\'est-ce que la certification JAKIM ?', answer: 'JAKIM (Jabatan Kemajuan Islam Malaysia) est le département gouvernemental malaisien qui certifie tous les établissements halal du pays. Cette certification annuelle renouvelable est la plus stricte au monde — voir le logo JAKIM = certitude absolue.' },
      { question: 'La Malaisie est-elle une bonne destination pour les familles ?', answer: 'Absolument. La Malaisie est l\'une des destinations familiales halal les plus complètes : parcs aquatiques, parcs naturels, plages, activités culturelles, restaurants adaptés aux enfants, transports excellents.' },
      { question: 'Quel est le coût de la vie en Malaisie ?', answer: 'La Malaisie est très abordable. Un repas halal certifié dans un food court coûte 2-4€. Un hôtel de standing moyen 40-80€/nuit. Budget total confortable : 60-100€/jour.' },
      { question: 'Quelle langue parle-t-on en Malaisie ?', answer: 'Le Bahasa Malaysia (malais) est la langue officielle, mais l\'anglais est largement parlé dans les villes et les zones touristiques. Pas de barrière linguistique pour les voyageurs francophones.' },
    ],
    tips: [
      'La carte Touch \'n Go est indispensable pour les transports en commun à KL.',
      'Grab est l\'application de transport de référence — fiable et moins cher que les taxis.',
      'Les food courts des centres commerciaux offrent une diversité culinaire halal certifiée incomparable.',
      'Préparer des tenues légères — chaleur et humidité élevées toute l\'année.',
      'La période du Thaïpusam (janvier-février) offre un spectacle culturel unique à Batu Caves.',
    ],
    tags: ['Halal certifié', 'Gastronomie', 'Nature', 'Moderne', 'Famille', 'Budget'],
  },
  {
    slug: 'arabie-saoudite',
    name: 'Arabie Saoudite',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=1400&q=85',
    flagEmoji: '🇸🇦',
    halalScore: 5,
    capitalCity: 'Riyad',
    population: '36 millions',
    muslimPercentage: '100%',
    currency: 'Riyal saoudien (SAR)',
    bestTime: 'Septembre–avril',
    shortDescription: 'Gardienne des deux mosquées saintes, l\'Arabie Saoudite est le voyage spirituel ultime de tout musulman.',
    description: 'L\'Arabie Saoudite est la terre sainte de l\'islam, accueillant chaque année des millions de pèlerins pour l\'Omra et le Hajj. La Mecque et Médine sont les destinations spirituelles les plus importantes pour tout musulman. Depuis 2019, l\'Arabie Saoudite a ouvert ses portes au tourisme mondial avec des e-visas facilités et de nombreuses nouvelles attractions (AlUla, Diriyah, NEOM). Au-delà de la dimension spirituelle, le pays offre un patrimoine archéologique exceptionnel et une gastronomie 100% halal dans un cadre islamique total.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Interdit',
    dresscode: 'Tenue islamique stricte pour les femmes dans les lieux saints. Dans les zones touristiques modernes, tenue modeste suffisante.',
    mainCities: [
      { name: 'La Mecque', slug: 'la-mecque', description: 'La ville la plus sainte de l\'islam — accessible uniquement aux musulmans.' },
      { name: 'Médine', slug: 'medine', description: 'Ville du Prophète ﷺ et de la Mosquée an-Nabawi — deuxième lieu saint de l\'islam.' },
      { name: 'Riyad', slug: 'riyad', description: 'Capitale moderne en pleine transformation, musées et centres commerciaux de classe mondiale.' },
      { name: 'AlUla', slug: 'alula', description: 'Site archéologique exceptionnel — Hegra classée UNESCO, splendeurs du désert.' },
    ],
    relatedGuides: [
      { slug: 'omra-2026-guide-complet', title: 'Omra 2026 : guide complet pour préparer votre pèlerinage', type: 'guide' },
      { slug: 'ramadan-voyage-guide', title: 'Voyager pendant le Ramadan : guide complet', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Les non-musulmans peuvent-ils entrer en Arabie Saoudite ?', answer: 'Oui, depuis 2019, l\'Arabie Saoudite délivre des visas touristiques aux non-musulmans. En revanche, La Mecque et Médine (centre-ville) restent réservées aux musulmans.' },
      { question: 'Comment obtenir un visa pour l\'Omra ?', answer: 'Via le portail officiel nusuk.sa pour un e-visa Omra (24-72h de délai) ou via une agence agréée française. Documents requis : passeport valide 6 mois + vaccination méningocoque ACWY.' },
      { question: 'Quelle est la différence entre Omra et Hajj ?', answer: 'L\'Omra est le "petit pèlerinage", réalisable toute l\'année, sans condition préalable. Le Hajj est le "grand pèlerinage", obligatoire pour tout musulman en capacité, à une date précise du calendrier islamique (Dhul Hijja). Le Hajj est l\'un des 5 piliers de l\'islam.' },
      { question: 'Quel budget prévoir pour l\'Omra depuis la France ?', answer: 'Vol Paris–Djeddah (350-700€) + hébergement (80-300€/nuit selon standing et distance de la Kaaba) + repas (30-60€/jour). Les forfaits Omra tout compris débutent à 1 200€ (hors saison) et peuvent dépasser 5 000€ pendant le Ramadan.' },
    ],
    tips: [
      'Réserver l\'Omra 3 à 6 mois à l\'avance, surtout pendant le Ramadan où les hôtels se remplissent des mois avant.',
      'L\'application Nusuk (officielle) est indispensable pour les réservations et informations en temps réel.',
      'Choisir l\'hôtel le plus proche de la Masjid al-Haram pour minimiser les distances à pied.',
      'S\'hydrater constamment — la chaleur peut atteindre 45°C en été à La Mecque.',
      'Emporter des vêtements adaptés (ihram pour les hommes, tenues amples pour les femmes).',
    ],
    tags: ['Spiritualité', 'Omra', 'Hajj', 'Pèlerinage', 'Islam', 'Patrimoine'],
  },
  {
    slug: 'egypte',
    name: 'Égypte',
    continent: 'Afrique',
    coverImage: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=1400&q=85',
    flagEmoji: '🇪🇬',
    halalScore: 5,
    capitalCity: 'Le Caire',
    population: '106 millions',
    muslimPercentage: '90%',
    currency: 'Livre égyptienne (EGP)',
    bestTime: 'Octobre–avril',
    shortDescription: 'Des pyramides de Gizeh à Al-Azhar, l\'Égypte conjugue merveilles antiques et richesse islamique.',
    description: 'L\'Égypte est une destination unique au monde : nulle part ailleurs on ne trouve cette combinaison d\'histoire antique (pyramides, sphinx, temples pharaoniques) et de richesse islamique (Al-Azhar, le Khan el-Khalili, 3 000 mosquées au Caire). Pays à 90% musulman, la nourriture halal est la norme absolue. Le Caire fascine par son intensité, Louxor et Assouan éblouissent par leurs temples, et les stations balnéaires de Charm el-Cheikh et Hurghada offrent mer et soleil dans un cadre accessible.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste dans les villes et les sites religieux. Plus de liberté dans les stations balnéaires.',
    mainCities: [
      { name: 'Le Caire', slug: 'le-caire', description: 'La mère du monde — pyramides, Al-Azhar, khan el-Khalili et une énergie unique.' },
      { name: 'Louxor', slug: 'louxor', description: 'La plus grande ville-musée à ciel ouvert du monde, temple de Karnak, Vallée des Rois.' },
      { name: 'Alexandrie', slug: 'alexandrie', description: 'Perle méditerranéenne, bibliothèque, gastronomie de fruits de mer, ambiance cosmopolite.' },
      { name: 'Charm el-Cheikh', slug: 'charm-el-cheikh', description: 'Plongée en mer Rouge, complexes hôteliers halal, coraux exceptionnels.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'ramadan-voyage-guide', title: 'Voyager pendant le Ramadan', type: 'guide' },
    ],
    faqs: [
      { question: 'Est-ce sûr de voyager en Égypte en 2026 ?', answer: 'Les zones touristiques (Le Caire, Louxor, Charm el-Cheikh, Hurghada) sont sûres et accueillent des millions de touristes chaque année. Le Ministère français des affaires étrangères recommande une vigilance normale dans ces zones.' },
      { question: 'Faut-il un visa pour l\'Égypte ?', answer: 'Oui, mais il est obtenu facilement en e-visa sur visa2egypt.gov.eg pour environ 25$, ou à l\'arrivée à l\'aéroport (25$). Valable 30 jours.' },
      { question: 'Quel budget pour un voyage en Égypte ?', answer: 'L\'Égypte est très abordable. Un repas local coûte 2-5€, un hôtel de qualité 30-60€/nuit. Budget confort : 50-100€/jour. Les billets d\'entrée des sites archéologiques (pyramides, temples) sont les principales dépenses touristiques.' },
    ],
    tips: [
      'Négocier est indispensable pour taxis, calèches et souvenirs — toujours demander le prix avant.',
      'Boire uniquement de l\'eau en bouteille — éviter l\'eau du robinet.',
      'Visiter les pyramides à l\'ouverture (7h) pour éviter la chaleur et les foules.',
      'Les pourboires (bakchich) font partie de la culture — prévoir de la monnaie.',
      'Se faire accompagner d\'un guide local pour les bazars — cela évite les arnaques et enrichit la visite.',
    ],
    tags: ['Histoire', 'Archéologie', 'Pyramides', 'Islam', 'Mer Rouge', 'Culture'],
  },
  {
    slug: 'maldives',
    name: 'Maldives',
    continent: 'Asie du Sud',
    coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1400&q=85',
    flagEmoji: '🇲🇻',
    halalScore: 4,
    capitalCity: 'Malé',
    population: '540 000',
    muslimPercentage: '100%',
    currency: 'Rufiyaa maldivienne (MVR)',
    bestTime: 'Novembre–avril',
    shortDescription: 'Lagons turquoise, villas sur pilotis et 100% pays musulman — le paradis accessible aux couples halal.',
    description: 'Les Maldives sont le paradis sur terre — et pour les couples musulmans, c\'est une bénédiction particulière. Pays islamique à 100%, l\'alcool est légalement interdit sur les îles habitées locales. Les resorts touristiques proposent des options halal-friendly avec villas privées, plages exclusives et piscines privées — permettant une intimité totale pour les jeunes mariés et les couples. Les lagons turquoise aux eaux cristallines, les fonds marins d\'une richesse inouïe et la quiétude absolue font des Maldives une destination lune de miel idéale.',
    halalFoodAvailability: 'Bon',
    mosquesPresence: 'Dans les villes',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste sur les îles habitées. Plus de liberté dans les resorts privés.',
    mainCities: [
      { name: 'Malé', slug: 'male', description: 'Capitale animée avec la Grande Mosquée du Vendredi, marché local coloré.' },
      { name: 'Maafushi', slug: 'maafushi', description: 'Île locale avec guest houses abordables, budget halal-friendly.' },
      { name: 'Atolls du Nord', slug: 'atolls-nord', description: 'Resorts de luxe avec overwater bungalows, snorkeling et plongée exceptionnels.' },
    ],
    relatedGuides: [
      { slug: 'lune-de-miel-halal', title: 'Lune de miel halal : 10 destinations romantiques', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Les Maldives sont-elles halal-friendly pour les couples musulmans ?', answer: 'Oui. Les Maldives sont un État islamique à 100%. Les resorts proposent de la nourriture halal, des espaces privés et une discrétion absolue. Les villas avec piscines privées sur pilotis offrent une intimité totale pour les couples.' },
      { question: 'Quel est le meilleur moyen de rejoindre son resort aux Maldives ?', answer: 'Après l\'atterrissage à Malé, vous rejoignez votre resort en hydravion (20-45 min, très cher), en speed boat (30-90 min, moins cher) ou en bateau local pour les îles proches.' },
      { question: 'Quel budget prévoir pour les Maldives ?', answer: 'Les Maldives s\'adaptent à tous les budgets. Les guest houses sur îles locales : 80-150€/nuit. Les resorts d\'entrée de gamme : 200-400€/nuit. Les resorts de luxe : 500€ à 5 000€/nuit.' },
    ],
    tips: [
      'Réserver 4 à 6 mois à l\'avance pour les meilleures offres, surtout en haute saison.',
      'Les îles locales (Maafushi, Fulidhoo) sont 3 à 5 fois moins chères que les resorts privés.',
      'Respecter les codes vestimentaires sur les îles habitées — bikinis autorisés uniquement sur les plages réservées aux touristes.',
      'Le snorkeling est souvent aussi spectaculaire que la plongée — et gratuit depuis la plage.',
      'Négocier les transferts en speed boat directement avec les hôtels — souvent inclus dans les packages.',
    ],
    tags: ['Lune de miel', 'Luxe', 'Plage', 'Snorkeling', 'Couple', 'Paradis'],
  },
  {
    slug: 'tunisie',
    name: 'Tunisie',
    continent: 'Afrique',
    coverImage: 'https://images.unsplash.com/photo-1539519532670-6a4e9eb65c13?w=1400&q=85',
    flagEmoji: '🇹🇳',
    halalScore: 4,
    capitalCity: 'Tunis',
    population: '12 millions',
    muslimPercentage: '99%',
    currency: 'Dinar tunisien (TND)',
    bestTime: 'Avril–juin · Septembre–novembre',
    shortDescription: 'La Méditerranée islamique — Carthage, Djerba, la médina de Tunis et une hospitalité légendaire.',
    description: 'La Tunisie est une destination halal magnifique et sous-estimée. À seulement 2h de vol de Paris, ce pays à majorité musulmane offre une combinaison unique : patrimoine punique et romain (Carthage, el-Jem), médinas islamiques classées UNESCO (Tunis, Kairouan, Sfax), plages turquoise et une gastronomie méditerranéenne authentiquement halal. Djerba, "l\'île aux mille et une nuits", est l\'une des destinations balnéaires halal les plus accessibles et les plus prisées des familles françaises.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Disponible mais évitable',
    dresscode: 'Tenue modeste recommandée dans les médinas et sites religieux. Plus décontracté dans les zones touristiques.',
    mainCities: [
      { name: 'Tunis', slug: 'tunis', description: 'Capitale avec la médina classée UNESCO, souk de la Médina, musée du Bardo.' },
      { name: 'Djerba', slug: 'djerba', description: 'Île aux plages de sable blanc, architecture berbère et ambiance méditerranéenne unique.' },
      { name: 'Kairouan', slug: 'kairouan', description: 'Quatrième ville sainte de l\'islam, Grande Mosquée, médina et artisanat traditionnel.' },
      { name: 'Sousse', slug: 'sousse', description: 'Station balnéaire avec médina classée UNESCO, resorts et plages.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'vacances-halal-famille-2026', title: 'Vacances halal en famille : idées 2026', type: 'guide' },
    ],
    faqs: [
      { question: 'Faut-il un visa pour la Tunisie ?', answer: 'Non. Les ressortissants français, belges et suisses peuvent entrer en Tunisie sans visa pour un séjour touristique de moins de 3 mois avec un simple passeport ou une carte d\'identité.' },
      { question: 'La Tunisie est-elle sûre pour les touristes en 2026 ?', answer: 'Oui, les zones touristiques (Tunis, Djerba, Sousse, Hammamet) sont sûres. Le Ministère français des Affaires Étrangères recommande une vigilance normale dans ces zones.' },
      { question: 'Quel budget pour la Tunisie ?', answer: 'La Tunisie est très abordable. Repas locaux : 3-8€. Hôtel de qualité : 30-70€/nuit. Budget tout compris confortable : 50-90€/jour.' },
    ],
    tips: [
      'Le dinar tunisien ne peut pas être exporté — changer uniquement ce dont vous avez besoin.',
      'Le taxi partagé (louage) est le moyen de transport le plus pratique entre villes.',
      'Négocier est habituel dans les marchés et pour les excursions.',
      'Kairouan est une destination spirituelle majeure pour les musulmans — à ne pas manquer.',
      'Les resorts all-inclusive servent parfois de l\'alcool dans les buffets — vérifier avant de réserver.',
    ],
    tags: ['Méditerranée', 'Plage', 'Histoire', 'Culture', 'Famille', 'Budget'],
  },
  {
    slug: 'qatar',
    name: 'Qatar',
    continent: 'Moyen-Orient',
    coverImage: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=1400&q=85',
    flagEmoji: '🇶🇦',
    halalScore: 5,
    capitalCity: 'Doha',
    population: '2.9 millions',
    muslimPercentage: '67%',
    currency: 'Riyal qatarien (QAR)',
    bestTime: 'Novembre–mars',
    shortDescription: 'Modernité ultracontemporaine et richesse islamique dans l\'un des États les plus riches du monde.',
    description: 'Le Qatar a émergé comme une destination touristique majeure depuis la Coupe du Monde 2022. Doha offre une skyline spectaculaire, des musées de classe mondiale (le Musée d\'Art Islamique est l\'un des plus beaux du monde), une gastronomie halal de qualité exceptionnelle et un accueil chaleureux. Petit État islamique mais ultra-moderne, le Qatar combine tradition bédouine (souk Waqif, désert de Khor Al Udaid) et contemporanéité absolue. La liaison Qatar Airways Paris–Doha est parmi les meilleures du monde.',
    halalFoodAvailability: 'Excellent',
    mosquesPresence: 'Partout',
    alcoholPolicy: 'Rare',
    dresscode: 'Tenue modeste dans les espaces publics. Respect des codes dans les mosquées et sites religieux.',
    mainCities: [
      { name: 'Doha', slug: 'doha', description: 'Capitale ultramoderne avec la corniche, le souk Waqif et des musées exceptionnels.' },
      { name: 'Al Wakrah', slug: 'al-wakrah', description: 'Ville côtière avec un souk traditionnel, moins touristique et plus authentique.' },
    ],
    relatedGuides: [
      { slug: 'top-destinations-halal-2026', title: 'Top 10 destinations halal 2026', type: 'guide' },
      { slug: 'hotel-halal-tout-savoir', title: 'Hôtel halal : tout ce qu\'il faut savoir', type: 'guide' },
    ],
    faqs: [
      { question: 'Faut-un visa pour le Qatar ?', answer: 'La plupart des ressortissants européens (dont les Français, Belges et Suisses) bénéficient d\'une entrée sans visa ou d\'un visa à l\'arrivée (gratuit, 30 jours). Vérifier sur le site de Qatar Airways.' },
      { question: 'Peut-on consommer de l\'alcool au Qatar ?', answer: 'L\'alcool est disponible dans les hôtels licenciés et certains restaurants, mais très facilement évitable. La grande majorité des restaurants qatariens n\'en servent pas.' },
    ],
    tips: [
      'Le souk Waqif à Doha est un incontournable pour l\'artisanat, les épices et l\'ambiance authentique.',
      'Le Musée d\'Art Islamique est une merveille architecturale — prévoir 2-3 heures.',
      'Le désert de Khor Al Udaid (dunes qui plongent dans la mer) est unique au monde.',
      'Qatar Airways propose souvent des escales à Doha incluses dans les billets longue distance — excellent moyen de visiter à moindre coût.',
    ],
    tags: ['Luxe', 'Culture', 'Moderne', 'Musées', 'Désert', 'Gastronomie'],
  },
]

export function getCountryBySlug(slug: string): Country | undefined {
  return countries.find((c) => c.slug === slug)
}
